/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AGUI;

import BLOGICA.Expresiones;
import BLOGICA.ManParqueadero;
import BLOGICA.ManPropietario;
import CLASES.Parqueadero;
import CLASES.Propietario;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author David
 */
public class GUI_RegistrarParqueadero extends javax.swing.JFrame {

    ManParqueadero ObjManParq = new ManParqueadero();
    Parqueadero ObjParq = new Parqueadero();
    Expresiones ObjExp = new Expresiones();
    Propietario ObjPro = new Propietario();
    ManPropietario ObjManPro = new ManPropietario(); 
    
    public GUI_RegistrarParqueadero() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombreP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCalleP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCalleS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSector = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<String>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSpinnerNPlazas = new javax.swing.JSpinner();
        jTextFieldTarifa = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldConfirmPassword = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldUser = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButtonConfirmar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Registrar Parqueadero");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 290, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre del Parqueadero:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTextFieldNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombrePActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 170, -1));

        jLabel3.setText("Calle Principal:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        jPanel2.add(jTextFieldCalleP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 170, -1));

        jLabel4.setText("Calle Secundaria:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel2.add(jTextFieldCalleS, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 170, -1));

        jLabel5.setText("Sector:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jPanel2.add(jTextFieldSector, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 170, -1));

        jLabel6.setText("Numero de Plazas:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel7.setText("Tarifa:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel9.setText("Datos del Parqueadero");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cerrado", "Abierto" }));
        jPanel2.add(jComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jLabel16.setText("Estado:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jLabel17.setText("0.75");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));
        jPanel2.add(jSpinnerNPlazas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 50, -1));
        jPanel2.add(jTextFieldTarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 50, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 500, 290));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Datos del Propietario");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel10.setText("Confirmar Contraseña:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel11.setText("Nombre:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel12.setText("Apellido:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel13.setText("Cedula:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel14.setText("Usuario:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel15.setText("Contraseña:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));
        jPanel3.add(jTextFieldConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 170, -1));
        jPanel3.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 170, -1));
        jPanel3.add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 170, -1));
        jPanel3.add(jTextFieldCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 170, -1));
        jPanel3.add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 170, -1));
        jPanel3.add(jTextFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 170, -1));
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 170, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 500, 230));

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, -1, -1));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 610, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombrePActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        int ok = 1;

        if(this.jTextFieldNombreP.getText() != null){
            ok = 1;
        }else{
            ok = 0;
            JOptionPane.showMessageDialog(null, "Ingrese un nombre para el parqueadero", "ERROR", JOptionPane.ERROR_MESSAGE);

        }

        if(this.jTextFieldCalleP.getText() != null){
            ok = 1;
        }else{
            ok = 0;
            JOptionPane.showMessageDialog(null, "El campo Calle Principal se encuentra vacio", "ERROR", JOptionPane.ERROR_MESSAGE);

        }

        if(this.jTextFieldCalleS.getText() != null){
            ok = 1;
        }else{
            ok = 0;
            JOptionPane.showMessageDialog(null, "El campo Calle Secundaria se encuentra vacio", "ERROR", JOptionPane.ERROR_MESSAGE);

        }

        if(this.jTextFieldSector.getText() != null){
            ok = 1;
        }else{
            ok = 0;
            JOptionPane.showMessageDialog(null, "El campo Sector se encuentra vacio", "ERROR", JOptionPane.ERROR_MESSAGE);

        }

        if(ok == 1){
            System.out.println(" chek ");
            
            ObjPro = ObjManPro.CrearPropietario(this.jTextFieldNombreP.getText(),
                    this.jTextFieldNombre.getText(), 
                    this.jTextFieldApellido.getText(),
                    this.jTextFieldCedula.getText(),
                    this.jTextFieldUser.getText(),
                    this.jTextFieldPassword.getText());
            
           /* ObjEst = ObjManEst.CambiarEstado(this.jTextFieldNombreP.getText(),
                    this.jComboBoxEstado.getSelectedItem().toString(), 
                    new Date(), 
                    this.jTextFieldObservaciones.getText());*/
            
            ObjParq = ObjManParq.RegistrarParqueadero(this.jTextFieldNombreP.getText(), 
                    this.jTextFieldCalleP.getText(),
                    this.jTextFieldCalleS.getText(),
                    this.jTextFieldSector.getText(),
                    Integer.parseInt(this.jSpinnerNPlazas.getValue().toString()),
                    Double.parseDouble(this.jTextFieldTarifa.getText()),
                    ObjPro,
                    String.valueOf(this.jComboBoxEstado.getSelectedItem().toString()));
            
            JOptionPane.showMessageDialog(null, ObjParq);
            
            try {
                ObjManParq.EscribirParqueaderos(ObjParq);
            } catch (IOException ex) {
                Logger.getLogger(GUI_RegistrarParqueadero.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                ObjManParq.EscribirPropietarios(ObjPro);
            } catch (IOException ex) {
                Logger.getLogger(GUI_RegistrarParqueadero.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_RegistrarParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_RegistrarParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_RegistrarParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_RegistrarParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_RegistrarParqueadero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinnerNPlazas;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCalleP;
    private javax.swing.JTextField jTextFieldCalleS;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldConfirmPassword;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombreP;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldSector;
    private javax.swing.JTextField jTextFieldTarifa;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
