/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AGUI;

import BLOGICA.Expresiones;
import BLOGICA.ManCliente;
import BLOGICA.ManVehiculo;
import CLASES.Cliente;
import CLASES.Vehiculo;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class GUI_RegistrarCliente extends javax.swing.JFrame {

    ManCliente ObjManCli = new ManCliente();
    Cliente ObjCli = new Cliente();
    ManVehiculo ObjManVeh = new ManVehiculo();
    Vehiculo ObjVeh = new Vehiculo();
    Expresiones ObjExp = new Expresiones();
    
    public GUI_RegistrarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelCorreoElectronico = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonConfirmarCliente = new javax.swing.JButton();
        jTextFieldCedula1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldCelular1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldPlaca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxTipoVehiculo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jButtonConfirmarVehiculo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldConfirmarPassword = new javax.swing.JTextField();
        jButtonConfirmarUsuario = new javax.swing.JButton();
        jButtonConfirmarRegistro = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Registrar Cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 210, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jTextFieldNombre.setText("David");
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 230, -1));

        jLabel4.setText("Apellido:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jTextFieldApellido.setText("Burneo");
        jTextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 230, -1));

        jLabel5.setText("Cedula:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jTextFieldCorreo.setText("davichov2013@gmail.com");
        jTextFieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreoActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 230, -1));

        jLabelCorreoElectronico.setText("E-Mail");
        jPanel2.add(jLabelCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel8.setText("Datos Personales");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jButtonConfirmarCliente.setText("Confirmar");
        jButtonConfirmarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonConfirmarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        jTextFieldCedula1.setText("1104745540");
        jTextFieldCedula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCedula1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 230, -1));

        jLabel17.setText("Celular:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jTextFieldCelular1.setText("0991211239");
        jTextFieldCelular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCelular1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldCelular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 230, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 520, 240));

        jLabel3.setText("Ingrese los datos solicitados para registrarse en el sistema");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 340, 20));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("LAA-0000");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 100, -1));

        jLabel10.setText("Placa");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jTextFieldPlaca.setText("PBS8585");
        jTextFieldPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlacaActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 130, -1));

        jLabel9.setText("Tipo de Vehiculo");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jComboBoxTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automovil", "Camioneta", "Buseta", "Camión pequeño" }));
        jPanel3.add(jComboBoxTipoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jLabel12.setText("Datos del Vehículo");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jButtonConfirmarVehiculo.setText("Confirmar");
        jButtonConfirmarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarVehiculoActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonConfirmarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 510, 190));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Datos Usuario");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel14.setText("Nombre de Usuario");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jTextFieldUser.setText("daburneo1");
        jTextFieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 170, -1));

        jLabel15.setText("Contraseña");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jTextFieldPassword.setText("dada");
        jPanel4.add(jTextFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 170, -1));

        jLabel16.setText("Confirmar Contraseña");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jTextFieldConfirmarPassword.setText("dada");
        jPanel4.add(jTextFieldConfirmarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 170, -1));

        jButtonConfirmarUsuario.setText("Confirmar");
        jPanel4.add(jButtonConfirmarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 520, 160));

        jButtonConfirmarRegistro.setText("Confirmar Registro");
        jButtonConfirmarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, -1, -1));

        jButton3.setText("Editar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, -1, -1));

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, -1, -1));

        jButton5.setText("Atras");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 620, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed

    private void jTextFieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoActionPerformed

    private void jTextFieldPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlacaActionPerformed

    private void jTextFieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserActionPerformed

    private void jButtonConfirmarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarClienteActionPerformed
        
    }//GEN-LAST:event_jButtonConfirmarClienteActionPerformed

    private void jButtonConfirmarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmarVehiculoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextFieldCedula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedula1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
          this.setVisible(false);
        GUI_Principal p = new GUI_Principal();
        p.setVisible(true);
                          
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonConfirmarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarRegistroActionPerformed
        int ok = 1;
        /*
        if(ObjExp.NumerosCedula(this.jTextFieldCedula1.getText()) && ObjExp.NumeroCelular(this.jTextFieldCorreo.getText()) && this.jTextFieldNombre.getText() != null && this.jTextFieldApellido.getText() != null){
            ok = 1;
        }else{
            ok = 0;
            
            JOptionPane.showMessageDialog(null, "Error con el ingreso de datos personales", "ERROR", JOptionPane.ERROR_MESSAGE); 
            
        }
        */
        
        if(ObjExp.NumerosCedula(this.jTextFieldCedula1.getText())){
            ok = 1;
        }else{
            ok = 0;
            JOptionPane.showMessageDialog(null, "Error con el ingreso de la cedula", "ERROR", JOptionPane.ERROR_MESSAGE); 
        }
        
        if(ObjExp.NumeroCelular(this.jTextFieldCelular1.getText())){
             ok = 1;
        }else{
            ok = 0;
            JOptionPane.showMessageDialog(null, "Error con el ingreso del numero de celular", "ERROR", JOptionPane.ERROR_MESSAGE); 
        }
        
        if(this.jTextFieldNombre.getText() != null){
           ok = 1;
        }else{
            ok = 0;
            JOptionPane.showMessageDialog(null, "Error con el ingreso del Nombre", "ERROR", JOptionPane.ERROR_MESSAGE);  
        }
        
        if(this.jTextFieldApellido.getText() != null){
            ok = 1;
        }else{
            ok = 0;
            JOptionPane.showMessageDialog(null, "Error con el ingreso del Apellido", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        if(ObjExp.mailValido(this.jTextFieldCorreo.getText())){
            ok = 1;
        }else{
            ok = 0;  
            JOptionPane.showMessageDialog(null, "Error con el ingreso del correo electronico", "ERROR", JOptionPane.ERROR_MESSAGE); 
        }
        
        if(ok == 1){
            
            ObjVeh = ObjManVeh.RegistrarVehiculo(this.jTextFieldPlaca.getText(), this.jComboBoxTipoVehiculo.getSelectedItem().toString(), this.jTextFieldCedula1.getText());
            
            ObjCli = ObjManCli.RegistrarCliente(this.jTextFieldNombre.getText(),
                            this.jTextFieldApellido.getText(),
                            this.jTextFieldCelular1.getText(),
                            this.jTextFieldCedula1.getText(),
                            this.jTextFieldUser.getText(),
                            this.jTextFieldPassword.getText(),
                            ObjVeh,
                            this.jTextFieldCorreo.getText());
            JOptionPane.showMessageDialog(null, ObjCli);
            try {
                ObjManCli.EscribirRegistros(ObjCli);
            } catch (IOException ex) {
                Logger.getLogger(GUI_RegistrarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Error con el ingreso de datos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        this.dispose();
        
        
    }//GEN-LAST:event_jButtonConfirmarRegistroActionPerformed

    private void jTextFieldCelular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCelular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCelular1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_RegistrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonConfirmarCliente;
    private javax.swing.JButton jButtonConfirmarRegistro;
    private javax.swing.JButton jButtonConfirmarUsuario;
    private javax.swing.JButton jButtonConfirmarVehiculo;
    private javax.swing.JComboBox<String> jComboBoxTipoVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCorreoElectronico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCedula1;
    private javax.swing.JTextField jTextFieldCelular1;
    private javax.swing.JTextField jTextFieldConfirmarPassword;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldPlaca;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
