/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AGUI;

/**
 *
 * @author David
 */
public class Reserva extends javax.swing.JFrame {

    /**
     * Creates new form Reserva
     */
    public Reserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButtonR20 = new javax.swing.JButton();
        jButtonR2 = new javax.swing.JButton();
        jButtonR3 = new javax.swing.JButton();
        jButtonR4 = new javax.swing.JButton();
        jButtonR5 = new javax.swing.JButton();
        jButtonR6 = new javax.swing.JButton();
        jButtonR7 = new javax.swing.JButton();
        jButtonR8 = new javax.swing.JButton();
        jButtonR9 = new javax.swing.JButton();
        jButtomR1 = new javax.swing.JButton();
        jButtonR11 = new javax.swing.JButton();
        jButtonR12 = new javax.swing.JButton();
        jButtonR13 = new javax.swing.JButton();
        jButtonR14 = new javax.swing.JButton();
        jButtonR15 = new javax.swing.JButton();
        jButtonR16 = new javax.swing.JButton();
        jButtonR17 = new javax.swing.JButton();
        jButtonR18 = new javax.swing.JButton();
        jButtonR19 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonCargarDatos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/vacio.png"))); // NOI18N
        jButton10.setText("jButton2");
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 50, -1));

        jButtonR20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/vacio.png"))); // NOI18N
        jButtonR20.setText("jButton2");
        jPanel1.add(jButtonR20, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 50, -1));

        jButtonR2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/carro1.png"))); // NOI18N
        jButtonR2.setText("jButton2");
        jButtonR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonR2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, -1));

        jButtonR3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/carro1.png"))); // NOI18N
        jButtonR3.setText("jButton2");
        jPanel1.add(jButtonR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 50, -1));

        jButtonR4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/carro1.png"))); // NOI18N
        jButtonR4.setText("jButton2");
        jButtonR4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonR4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 50, -1));

        jButtonR5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/vacio.png"))); // NOI18N
        jButtonR5.setText("jButton2");
        jPanel1.add(jButtonR5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 50, -1));

        jButtonR6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/carro1.png"))); // NOI18N
        jButtonR6.setText("jButton2");
        jPanel1.add(jButtonR6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 50, -1));

        jButtonR7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/vacio.png"))); // NOI18N
        jButtonR7.setText("jButton2");
        jButtonR7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonR7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonR7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 50, -1));

        jButtonR8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/vacio.png"))); // NOI18N
        jButtonR8.setText("jButton2");
        jPanel1.add(jButtonR8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 50, -1));

        jButtonR9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/vacio.png"))); // NOI18N
        jButtonR9.setText("jButton2");
        jPanel1.add(jButtonR9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 50, -1));

        jButtomR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/vacio.png"))); // NOI18N
        jButtomR1.setText("jButton2");
        jButtomR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtomR1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtomR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, -1));

        jButtonR11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/carro1.png"))); // NOI18N
        jButtonR11.setText("jButton2");
        jPanel1.add(jButtonR11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 50, -1));

        jButtonR12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/vacio.png"))); // NOI18N
        jButtonR12.setText("jButton2");
        jButtonR12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonR12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonR12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 50, -1));

        jButtonR13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/vacio.png"))); // NOI18N
        jButtonR13.setText("jButton2");
        jPanel1.add(jButtonR13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 50, -1));

        jButtonR14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/vacio.png"))); // NOI18N
        jButtonR14.setText("jButton2");
        jPanel1.add(jButtonR14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 50, -1));

        jButtonR15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/vacio.png"))); // NOI18N
        jButtonR15.setText("jButton2");
        jPanel1.add(jButtonR15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 50, -1));

        jButtonR16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/vacio.png"))); // NOI18N
        jButtonR16.setText("jButton2");
        jPanel1.add(jButtonR16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 50, -1));

        jButtonR17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/vacio.png"))); // NOI18N
        jButtonR17.setText("jButton2");
        jPanel1.add(jButtonR17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 50, -1));

        jButtonR18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/vacio.png"))); // NOI18N
        jButtonR18.setText("jButton2");
        jPanel1.add(jButtonR18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 50, -1));

        jButtonR19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/vacio.png"))); // NOI18N
        jButtonR19.setText("jButton2");
        jPanel1.add(jButtonR19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 50, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 610, 260));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setText("GESTION DE ESTACIONAMIENTO");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 280, 30));

        jButtonCargarDatos.setText("Cargar Datos");
        jPanel3.add(jButtonCargarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jLabel2.setText("Fecha");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel3.setText("Hora llegada:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel4.setText("Hora salida:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel5.setText("Plaza:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel6.setText("Estado");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel7.setText("Placa");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jTextField1.setEditable(false);
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 130, -1));

        jTextFieldFecha.setEditable(false);
        jPanel3.add(jTextFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 130, -1));

        jTextField3.setEditable(false);
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 130, -1));

        jTextField4.setEditable(false);
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 130, -1));

        jTextField5.setEditable(false);
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 130, -1));

        jTextField6.setEditable(false);
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 130, -1));

        jButtonConfirmar.setText("Confirmar");
        jPanel3.add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 380, 480));

        jLabel8.setText("Usuario");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jTextFieldUsuario.setEditable(false);
        jPanel2.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 220, -1));

        jLabel9.setText("Vehiculo");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jTextField2.setEditable(false);
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 220, -1));

        jLabel10.setText("Parqueadero: ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 310, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1110, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonR4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonR4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonR4ActionPerformed

    private void jButtomR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtomR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtomR1ActionPerformed

    private void jButtonR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonR2ActionPerformed

    private void jButtonR7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonR7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonR7ActionPerformed

    private void jButtonR12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonR12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonR12ActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtomR1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCargarDatos;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonR11;
    private javax.swing.JButton jButtonR12;
    private javax.swing.JButton jButtonR13;
    private javax.swing.JButton jButtonR14;
    private javax.swing.JButton jButtonR15;
    private javax.swing.JButton jButtonR16;
    private javax.swing.JButton jButtonR17;
    private javax.swing.JButton jButtonR18;
    private javax.swing.JButton jButtonR19;
    private javax.swing.JButton jButtonR2;
    private javax.swing.JButton jButtonR20;
    private javax.swing.JButton jButtonR3;
    private javax.swing.JButton jButtonR4;
    private javax.swing.JButton jButtonR5;
    private javax.swing.JButton jButtonR6;
    private javax.swing.JButton jButtonR7;
    private javax.swing.JButton jButtonR8;
    private javax.swing.JButton jButtonR9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
